/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated.alerts'
import { Route as AuthenticatedMembersRouteImport } from './routes/_authenticated.members'
import { Route as AuthenticatedOverviewRouteImport } from './routes/_authenticated.overview'
import { Route as AuthenticatedSshKeysRouteImport } from './routes/_authenticated.ssh-keys'
import { Route as AuthenticatedStatusRouteImport } from './routes/_authenticated.status'
import { Route as AuthenticatedHostsIndexRouteImport } from './routes/_authenticated.hosts.index'
import { Route as AuthenticatedHostsHostIdRouteImport } from './routes/_authenticated.hosts.$hostId'
import { Route as AuthenticatedHostsNewRouteImport } from './routes/_authenticated.hosts.new'
import { Route as AuthenticatedInstancesIndexRouteImport } from './routes/_authenticated.instances.index'
import { Route as AuthenticatedInstancesInstanceIdRouteImport } from './routes/_authenticated.instances.$instanceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMembersRoute = AuthenticatedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOverviewRoute = AuthenticatedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSshKeysRoute = AuthenticatedSshKeysRouteImport.update({
  id: '/ssh-keys',
  path: '/ssh-keys',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStatusRoute = AuthenticatedStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHostsIndexRoute = AuthenticatedHostsIndexRouteImport.update({
  id: '/hosts/',
  path: '/hosts/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHostsHostIdRoute =
  AuthenticatedHostsHostIdRouteImport.update({
    id: '/hosts/$hostId',
    path: '/hosts/$hostId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHostsNewRoute = AuthenticatedHostsNewRouteImport.update({
  id: '/hosts/new',
  path: '/hosts/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInstancesIndexRoute =
  AuthenticatedInstancesIndexRouteImport.update({
    id: '/instances/',
    path: '/instances/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstancesInstanceIdRoute =
  AuthenticatedInstancesInstanceIdRouteImport.update({
    id: '/instances/$instanceId',
    path: '/instances/$instanceId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/sign-in': typeof SignInRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/members': typeof AuthenticatedMembersRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/ssh-keys': typeof AuthenticatedSshKeysRoute
  '/status': typeof AuthenticatedStatusRoute
  '/hosts/$hostId': typeof AuthenticatedHostsHostIdRoute
  '/hosts/new': typeof AuthenticatedHostsNewRoute
  '/instances/$instanceId': typeof AuthenticatedInstancesInstanceIdRoute
  '/hosts/': typeof AuthenticatedHostsIndexRoute
  '/instances/': typeof AuthenticatedInstancesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/sign-in': typeof SignInRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/members': typeof AuthenticatedMembersRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/ssh-keys': typeof AuthenticatedSshKeysRoute
  '/status': typeof AuthenticatedStatusRoute
  '/hosts/$hostId': typeof AuthenticatedHostsHostIdRoute
  '/hosts/new': typeof AuthenticatedHostsNewRoute
  '/instances/$instanceId': typeof AuthenticatedInstancesInstanceIdRoute
  '/hosts': typeof AuthenticatedHostsIndexRoute
  '/instances': typeof AuthenticatedInstancesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/sign-in': typeof SignInRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/members': typeof AuthenticatedMembersRoute
  '/_authenticated/overview': typeof AuthenticatedOverviewRoute
  '/_authenticated/ssh-keys': typeof AuthenticatedSshKeysRoute
  '/_authenticated/status': typeof AuthenticatedStatusRoute
  '/_authenticated/hosts/$hostId': typeof AuthenticatedHostsHostIdRoute
  '/_authenticated/hosts/new': typeof AuthenticatedHostsNewRoute
  '/_authenticated/instances/$instanceId': typeof AuthenticatedInstancesInstanceIdRoute
  '/_authenticated/hosts/': typeof AuthenticatedHostsIndexRoute
  '/_authenticated/instances/': typeof AuthenticatedInstancesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/sign-in'
    | '/alerts'
    | '/members'
    | '/overview'
    | '/ssh-keys'
    | '/status'
    | '/hosts/$hostId'
    | '/hosts/new'
    | '/instances/$instanceId'
    | '/hosts/'
    | '/instances/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invitation'
    | '/sign-in'
    | '/alerts'
    | '/members'
    | '/overview'
    | '/ssh-keys'
    | '/status'
    | '/hosts/$hostId'
    | '/hosts/new'
    | '/instances/$instanceId'
    | '/hosts'
    | '/instances'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accept-invitation'
    | '/sign-in'
    | '/_authenticated/alerts'
    | '/_authenticated/members'
    | '/_authenticated/overview'
    | '/_authenticated/ssh-keys'
    | '/_authenticated/status'
    | '/_authenticated/hosts/$hostId'
    | '/_authenticated/hosts/new'
    | '/_authenticated/instances/$instanceId'
    | '/_authenticated/hosts/'
    | '/_authenticated/instances/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/members': {
      id: '/_authenticated/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthenticatedMembersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/overview': {
      id: '/_authenticated/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedOverviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ssh-keys': {
      id: '/_authenticated/ssh-keys'
      path: '/ssh-keys'
      fullPath: '/ssh-keys'
      preLoaderRoute: typeof AuthenticatedSshKeysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/status': {
      id: '/_authenticated/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof AuthenticatedStatusRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hosts/': {
      id: '/_authenticated/hosts/'
      path: '/hosts'
      fullPath: '/hosts/'
      preLoaderRoute: typeof AuthenticatedHostsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hosts/$hostId': {
      id: '/_authenticated/hosts/$hostId'
      path: '/hosts/$hostId'
      fullPath: '/hosts/$hostId'
      preLoaderRoute: typeof AuthenticatedHostsHostIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hosts/new': {
      id: '/_authenticated/hosts/new'
      path: '/hosts/new'
      fullPath: '/hosts/new'
      preLoaderRoute: typeof AuthenticatedHostsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instances/': {
      id: '/_authenticated/instances/'
      path: '/instances'
      fullPath: '/instances/'
      preLoaderRoute: typeof AuthenticatedInstancesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instances/$instanceId': {
      id: '/_authenticated/instances/$instanceId'
      path: '/instances/$instanceId'
      fullPath: '/instances/$instanceId'
      preLoaderRoute: typeof AuthenticatedInstancesInstanceIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedMembersRoute: typeof AuthenticatedMembersRoute
  AuthenticatedOverviewRoute: typeof AuthenticatedOverviewRoute
  AuthenticatedSshKeysRoute: typeof AuthenticatedSshKeysRoute
  AuthenticatedStatusRoute: typeof AuthenticatedStatusRoute
  AuthenticatedHostsHostIdRoute: typeof AuthenticatedHostsHostIdRoute
  AuthenticatedHostsNewRoute: typeof AuthenticatedHostsNewRoute
  AuthenticatedInstancesInstanceIdRoute: typeof AuthenticatedInstancesInstanceIdRoute
  AuthenticatedHostsIndexRoute: typeof AuthenticatedHostsIndexRoute
  AuthenticatedInstancesIndexRoute: typeof AuthenticatedInstancesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedMembersRoute: AuthenticatedMembersRoute,
  AuthenticatedOverviewRoute: AuthenticatedOverviewRoute,
  AuthenticatedSshKeysRoute: AuthenticatedSshKeysRoute,
  AuthenticatedStatusRoute: AuthenticatedStatusRoute,
  AuthenticatedHostsHostIdRoute: AuthenticatedHostsHostIdRoute,
  AuthenticatedHostsNewRoute: AuthenticatedHostsNewRoute,
  AuthenticatedInstancesInstanceIdRoute: AuthenticatedInstancesInstanceIdRoute,
  AuthenticatedHostsIndexRoute: AuthenticatedHostsIndexRoute,
  AuthenticatedInstancesIndexRoute: AuthenticatedInstancesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AcceptInvitationRoute: AcceptInvitationRoute,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
