/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthenticatedSshKeysRouteImport } from './routes/_authenticated.ssh-keys'
import { Route as AuthenticatedHostsIndexRouteImport } from './routes/_authenticated.hosts.index'
import { Route as AuthenticatedHostsHostIdRouteImport } from './routes/_authenticated.hosts.$hostId'
import { Route as AuthenticatedHostsNewRouteImport } from './routes/_authenticated.hosts.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSshKeysRoute = AuthenticatedSshKeysRouteImport.update({
  id: '/ssh-keys',
  path: '/ssh-keys',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHostsIndexRoute = AuthenticatedHostsIndexRouteImport.update({
  id: '/hosts/',
  path: '/hosts/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHostsHostIdRoute =
  AuthenticatedHostsHostIdRouteImport.update({
    id: '/hosts/$hostId',
    path: '/hosts/$hostId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHostsNewRoute = AuthenticatedHostsNewRouteImport.update({
  id: '/hosts/new',
  path: '/hosts/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/sign-in': typeof SignInRoute
  '/ssh-keys': typeof AuthenticatedSshKeysRoute
  '/hosts/$hostId': typeof AuthenticatedHostsHostIdRoute
  '/hosts/new': typeof AuthenticatedHostsNewRoute
  '/hosts/': typeof AuthenticatedHostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/sign-in': typeof SignInRoute
  '/ssh-keys': typeof AuthenticatedSshKeysRoute
  '/hosts/$hostId': typeof AuthenticatedHostsHostIdRoute
  '/hosts/new': typeof AuthenticatedHostsNewRoute
  '/hosts': typeof AuthenticatedHostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/sign-in': typeof SignInRoute
  '/_authenticated/ssh-keys': typeof AuthenticatedSshKeysRoute
  '/_authenticated/hosts/$hostId': typeof AuthenticatedHostsHostIdRoute
  '/_authenticated/hosts/new': typeof AuthenticatedHostsNewRoute
  '/_authenticated/hosts/': typeof AuthenticatedHostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/sign-in'
    | '/ssh-keys'
    | '/hosts/$hostId'
    | '/hosts/new'
    | '/hosts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invitation'
    | '/sign-in'
    | '/ssh-keys'
    | '/hosts/$hostId'
    | '/hosts/new'
    | '/hosts'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accept-invitation'
    | '/sign-in'
    | '/_authenticated/ssh-keys'
    | '/_authenticated/hosts/$hostId'
    | '/_authenticated/hosts/new'
    | '/_authenticated/hosts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ssh-keys': {
      id: '/_authenticated/ssh-keys'
      path: '/ssh-keys'
      fullPath: '/ssh-keys'
      preLoaderRoute: typeof AuthenticatedSshKeysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hosts/': {
      id: '/_authenticated/hosts/'
      path: '/hosts'
      fullPath: '/hosts/'
      preLoaderRoute: typeof AuthenticatedHostsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hosts/$hostId': {
      id: '/_authenticated/hosts/$hostId'
      path: '/hosts/$hostId'
      fullPath: '/hosts/$hostId'
      preLoaderRoute: typeof AuthenticatedHostsHostIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hosts/new': {
      id: '/_authenticated/hosts/new'
      path: '/hosts/new'
      fullPath: '/hosts/new'
      preLoaderRoute: typeof AuthenticatedHostsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedSshKeysRoute: typeof AuthenticatedSshKeysRoute
  AuthenticatedHostsHostIdRoute: typeof AuthenticatedHostsHostIdRoute
  AuthenticatedHostsNewRoute: typeof AuthenticatedHostsNewRoute
  AuthenticatedHostsIndexRoute: typeof AuthenticatedHostsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSshKeysRoute: AuthenticatedSshKeysRoute,
  AuthenticatedHostsHostIdRoute: AuthenticatedHostsHostIdRoute,
  AuthenticatedHostsNewRoute: AuthenticatedHostsNewRoute,
  AuthenticatedHostsIndexRoute: AuthenticatedHostsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AcceptInvitationRoute: AcceptInvitationRoute,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
