import { z } from "zod"

export const ERROR_CODES = [
	"UNAUTHORIZED",
	"FORBIDDEN",
	"HOST_NOT_FOUND",
	"SSH_KEY_NOT_FOUND",
	"FINGERPRINT_MISMATCH",
	"HOST_MISCONFIGURED",
	"HOST_UNREACHABLE",
	"HOST_PROVISIONING_FAILED",
	"HOST_CONCURRENTLY_MODIFIED",
	"HOST_PROVISIONING_IN_PROGRESS",
	"INVITATION_NOT_FOUND",
	"SSH_KEY_IN_USE",
	"HOST_NAME_TAKEN",
	"SSH_KEY_NAME_TAKEN",
	"INSTANCE_NOT_FOUND",
	"INSTANCE_CONFIG_UNUSABLE",
	"INSTANCE_BOT_CONFIG_UNUSABLE",
	"INSTANCE_HOST_NOT_READY",
	"INSTANCE_ACCOUNT_NOT_INTERACTIVE",
	"INSTANCE_COMMAND_NOT_ALLOWED",
	"INSTANCE_LIVE_CONTROL_REJECTED",
	"HOST_CHANNEL_LIMIT",
	"INSTANCE_LIVE_CONTROL_UNREADABLE",
	"INSTANCE_AUTH_IN_PROGRESS",
	"INSTANCE_CONCURRENTLY_MODIFIED",
	"INSTANCE_STILL_IN_USE",
	"INSTANCE_REMOVAL_FAILED",
	"INSTANCE_NAME_TAKEN",
	"HOST_HAS_INSTANCES",
	"SELF_HOST_UNAVAILABLE",
	"DESTINATION_REJECTED",
	"DESTINATION_NOT_FOUND",
	"DESTINATION_TEST_THROTTLED",
	"ORGANIZATION_TEST_THROTTLED",
	"DESTINATION_DISABLED",
	"DESTINATION_KIND_IMMUTABLE",
	"DESTINATION_NO_SIGNING_KEY",
	"DESTINATION_POINTS_HERE",
	"DESTINATION_NOT_PUBLIC",
	"DESTINATION_NOT_USABLE",
	"DESTINATION_NOT_AN_ADDRESS",
	"DESTINATION_NOT_HTTPS",
	"DESTINATION_HAS_CREDENTIALS",
	"DESTINATION_HAS_FRAGMENT",
	"DESTINATION_WRONG_HOST",
	"DESTINATION_ADDRESS_RETIRED",
	"DESTINATION_REQUIRES_SIGN_IN",
	"DESTINATION_HAS_PARAMETERS",
	"CONSTRAINT_VIOLATION",
] as const

export const errorCodeSchema = z.enum(ERROR_CODES)

export type ErrorCode = z.infer<typeof errorCodeSchema>

const ERROR_CODE_SET: ReadonlySet<string> = new Set(ERROR_CODES)

export const isErrorCode = (value: string | undefined): value is ErrorCode =>
	value !== undefined && ERROR_CODE_SET.has(value)
